## Cleaning Principles

1. Raw CSV files are not modified.
2. Cleaning is performed on working/processed datasets.
3. Missing values are not automatically deleted.
4. Suspicious values are investigated before removal.
5. Date columns are converted to datetime where date-based analysis is required.
6. Business rules are defined before cleaning.
7. Cleaned data is validated against the original data.
8. All important cleaning decisions are documented.

In [2]:
import pandas as pd

In [3]:
customers = pd.read_csv("../data/raw/customers.csv")

In [4]:
customers.head()

,customer_id,customer_name,gender,age,state,signup_date,acquisition_channel,city
0,C000001,Customer_000001,Male,59,Kerala,2025-01-30 05:14:27,Organic Search,Thiruvananthapuram
1,C000002,Customer_000002,Female,21,Karnataka,2024-10-18 21:17:16,Facebook,Bengaluru
2,C000003,Customer_000003,Female,38,Tamil Nadu,2024-10-20 08:38:02,Organic Search,Chennai
3,C000004,Customer_000004,Female,30,Rajasthan,2023-09-02 00:03:08,Organic Search,Jaipur
4,C000005,Customer_000005,Male,59,Kerala,2023-06-04 02:38:12,Facebook,Kochi

In [5]:
customers.tail()

,customer_id,customer_name,gender,age,state,signup_date,acquisition_channel,city
30045,C004350,Customer_004350,Male,33,Karnataka,2025-01-22 05:56:10,Organic Search,Bengaluru
30046,C016187,Customer_016187,Male,28,Maharashtra,2024-09-15 02:58:28,Google Ads,Nagpur
30047,C025053,Customer_025053,Male,29,Kerala,2023-01-26 14:53:07,Referral,Kochi
30048,C026040,Customer_026040,Female,64,Karnataka,2024-03-27 16:00:21,Organic Search,Mysuru
30049,C016068,Customer_016068,Male,52,West Bengal,2024-02-05 22:43:33,Google Ads,Kolkata

In [6]:
customers.shape

(30050, 8)

In [7]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 30050 entries, 0 to 30049
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          30050 non-null  str
 1   customer_name        30050 non-null  str
 2   gender               30050 non-null  str
 3   age                  30050 non-null  int64
 4   state                30050 non-null  str
 5   signup_date          30050 non-null  str
 6   acquisition_channel  30050 non-null  str
 7   city                 29749 non-null  str
dtypes: int64(1), str(7)
memory usage: 3.9 MB

In [8]:
customers.isnull().sum()

customer_id              0
customer_name            0
gender                   0
age                      0
state                    0
signup_date              0
acquisition_channel      0
city                   301
dtype: int64

In [9]:
customers["customer_id"].duplicated().sum()

np.int64(50)

In [10]:
customers.duplicated().sum()

np.int64(50)

In [11]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"])

In [12]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 30050 entries, 0 to 30049
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          30050 non-null  str
 1   customer_name        30050 non-null  str
 2   gender               30050 non-null  str
 3   age                  30050 non-null  int64
 4   state                30050 non-null  str
 5   signup_date          30050 non-null  datetime64[us]
 6   acquisition_channel  30050 non-null  str
 7   city                 29749 non-null  str
dtypes: datetime64[us](1), int64(1), str(6)
memory usage: 3.4 MB

In [13]:
customers["age"].describe()

count    30050.000000
mean        41.646922
std         13.847529
min         18.000000
25%         30.000000
50%         42.000000
75%         54.000000
max         65.000000
Name: age, dtype: float64

In [14]:
customers[(customers["age"] < 18) | (customers["age"] > 100)]

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, state, signup_date, acquisition_channel, city]
Index: []

In [15]:
customers[(customers["age"] < 18) | (customers["age"] > 100)]

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, state, signup_date, acquisition_channel, city]
Index: []

In [16]:
customers["gender"].value_counts()

gender
Male      14813
Female    14049
Other      1188
Name: count, dtype: int64

In [17]:
customers["state"].value_counts()

state
Telangana        3054
Uttar Pradesh    3043
Delhi            3040
West Bengal      3035
Rajasthan        3023
Tamil Nadu       3013
Karnataka        3008
Kerala           2956
Maharashtra      2943
Gujarat          2935
Name: count, dtype: int64

In [18]:
customers["acquisition_channel"].value_counts()

acquisition_channel
Organic Search    8218
Google Ads        6562
Referral          4479
Instagram         4259
Facebook          3596
Email             2936
Name: count, dtype: int64

In [19]:
customers["signup_date"].min(), customers["signup_date"].max()

(Timestamp('2023-01-01 00:53:32'), Timestamp('2025-12-30 23:08:37'))

In [20]:
customers[customers["signup_date"] > "2025-12-31"]

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, state, signup_date, acquisition_channel, city]
Index: []

In [21]:
customers.duplicated().sum()

np.int64(50)

In [22]:
customers["customer_id"].isnull().sum()

np.int64(0)

In [23]:
customers.isnull().mean().mul(100).round(2)

customer_id            0.0
customer_name          0.0
gender                 0.0
age                    0.0
state                  0.0
signup_date            0.0
acquisition_channel    0.0
city                   1.0
dtype: float64

In [24]:
orders = pd.read_csv("../data/raw/orders.csv")

In [25]:
orders.shape

(120000, 6)

In [26]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      120000 non-null  str
 1   customer_id   120000 non-null  str
 2   order_date    120000 non-null  str
 3   order_status  120000 non-null  str
 4   shipping_id   120000 non-null  str
 5   payment_id    120000 non-null  str
dtypes: str(6)
memory usage: 12.7 MB

In [27]:
orders.head(4)

,order_id,customer_id,order_date,order_status,shipping_id,payment_id
0,O0000001,C019000,2025-09-29 23:09:30,Cancelled,SHP0000001,PAY0000001
1,O0000002,C006312,2024-03-17 01:29:25,Completed,SHP0000002,PAY0000002
2,O0000003,C020502,2024-10-06 00:52:34,Completed,SHP0000003,PAY0000003
3,O0000004,C006131,2024-01-18 05:08:43,Completed,SHP0000004,PAY0000004

In [28]:
orders.isnull().sum()

order_id        0
customer_id     0
order_date      0
order_status    0
shipping_id     0
payment_id      0
dtype: int64

In [29]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [30]:
orders["customer_id"].isnull().sum()

np.int64(0)

In [31]:
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [32]:
orders["order_date"].min(), orders["order_date"].max()

(Timestamp('2024-01-01 00:00:04'), Timestamp('2025-12-30 23:54:49'))

In [33]:
orders["order_status"].value_counts()

order_status
Completed    105752
Cancelled      7171
Returned       7077
Name: count, dtype: int64

In [34]:
orders["order_status"].unique()

<ArrowStringArray>
['Cancelled', 'Completed', 'Returned']
Length: 3, dtype: str

In [35]:
orders["customer_id"].isin(customers["customer_id"]).value_counts()

customer_id
True    120000
Name: count, dtype: int64

In [36]:
orders["order_status"].value_counts(dropna=False)

order_status
Completed    105752
Cancelled      7171
Returned       7077
Name: count, dtype: int64

In [37]:
orders["order_id"].nunique(), len(orders)

(120000, 120000)

In [38]:
orders[["order_id", "customer_id"]].duplicated().sum()

np.int64(0)

In [39]:
orders["order_date"].isnull().sum()

np.int64(0)

In [40]:
orders[
    (orders["order_date"] < "2024-01-01") |
    (orders["order_date"] > "2025-12-31")
]

Empty DataFrame
Columns: [order_id, customer_id, order_date, order_status, shipping_id, payment_id]
Index: []

In [41]:
order_items = pd.read_csv("../data/raw/order_items.csv")

In [42]:
order_items.head(4)

  order_item_id  order_id product_id  quantity  unit_price  discount_amount
0    OI00000001  O0000001     P00937         1       88.29              0.0
1    OI00000002  O0000002     P00418         1      568.68              0.0
2    OI00000003  O0000002     P00088         4      105.00             63.0
3    OI00000004  O0000002     P00304         3       95.34             28.6

In [43]:
order_items.shape

(226739, 6)

In [44]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 226739 entries, 0 to 226738
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_item_id    226739 non-null  str
 1   order_id         226739 non-null  str
 2   product_id       226739 non-null  str
 3   quantity         226739 non-null  int64
 4   unit_price       226739 non-null  float64
 5   discount_amount  226739 non-null  float64
dtypes: float64(2), int64(1), str(3)
memory usage: 15.6 MB

In [45]:
order_items.isnull().sum()

order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price         0
discount_amount    0
dtype: int64

In [46]:
order_items["order_item_id"].duplicated().sum()

np.int64(0)

In [47]:
order_items["order_id"].isin(orders["order_id"]).value_counts()

order_id
True    226739
Name: count, dtype: int64

In [48]:
order_items[["quantity", "unit_price", "discount_amount"]].describe()

            quantity     unit_price  discount_amount
count  226739.000000  226739.000000    226739.000000
mean        1.381774     337.520376        42.570657
std         0.690190     254.036033        70.164715
min        -1.000000      34.180000         0.000000
25%         1.000000     174.950000         0.000000
50%         1.000000     266.150000        21.670000
75%         2.000000     418.430000        53.250000
max         4.000000    1951.530000      2023.870000

In [49]:
order_items[order_items["quantity"] < 0]

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount
36873,OI00036874,O0019464,P00969,-1,588.42,88.26
72989,OI00072990,O0038555,P00165,-1,337.05,0.00
89183,OI00089184,O0047093,P00750,-1,448.10,134.43
109838,OI00109839,O0058061,P00917,-1,129.58,58.31
122825,OI00122826,O0064997,P00676,-1,133.11,19.97
126107,OI00126108,O0066702,P00368,-1,143.97,43.19
133020,OI00133021,O0070318,P00903,-1,267.00,0.00
147669,OI00147670,O0078171,P00656,-1,223.36,22.34
166958,OI00166959,O0088352,P00836,-1,224.23,0.00
176574,OI00176575,O0093465,P00428,-1,177.98,0.00
177152,OI00177153,O0093773,P00750,-1,448.10,44.81
180496,OI00180497,O0095571,P00785,-1,349.05,34.90
190069,OI00190070,O0100555,P00775,-1,117.71,17.66
191132,OI00191133,O0101115,P00117,-1,481.90,24.09
216536,OI00216537,O0114645,P00554,-1,167.17,8.36

In [50]:
order_items[order_items["quantity"] == 0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_amount]
Index: []

In [51]:
order_items[order_items["unit_price"] < 0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_amount]
Index: []

In [52]:
order_items[order_items["discount_amount"] < 0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_amount]
Index: []

In [53]:
order_items["gross_value"] = (
    order_items["quantity"] * order_items["unit_price"]
)

In [54]:
order_items[
    order_items["discount_amount"] > order_items["gross_value"]
]

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount,gross_value
3216,OI00003217,O0001715,P00725,1,426.25,639.375,426.25
12051,OI00012052,O0006445,P00614,1,263.26,394.890,263.26
27456,OI00027457,O0014578,P00952,2,340.39,1021.170,680.78
36873,OI00036874,O0019464,P00969,-1,588.42,88.260,-588.42
56182,OI00056183,O0029727,P00089,2,337.09,1011.270,674.18
72989,OI00072990,O0038555,P00165,-1,337.05,0.000,-337.05
89183,OI00089184,O0047093,P00750,-1,448.10,134.430,-448.10
90704,OI00090705,O0047859,P00371,1,216.55,324.825,216.55
93594,OI00093595,O0049433,P00911,3,211.91,953.595,635.73
109838,OI00109839,O0058061,P00917,-1,129.58,58.310,-129.58
122825,OI00122826,O0064997,P00676,-1,133.11,19.970,-133.11
123840,OI00123841,O0065529,P00378,1,474.14,711.210,474.14
126107,OI00126108,O0066702,P00368,-1,143.97,43.190,-143.97
133020,OI00133021,O0070318,P00903,-1,267.00,0.000,-267.00
147669,OI00147670,O0078171,P00656,-1,223.36,22.340,-223.36
162065,OI00162066,O0085756,P00036,1,246.36,369.540,246.36
166958,OI00166959,O0088352,P00836,-1,224.23,0.000,-224.23
170741,OI00170742,O0090351,P00583,1,809.66,1214.490,809.66
176574,OI00176575,O0093465,P00428,-1,177.98,0.000,-177.98
177152,OI00177153,O0093773,P00750,-1,448.10,44.810,-448.10
178631,OI00178632,O0094565,P00818,1,138.59,207.885,138.59
180496,OI00180497,O0095571,P00785,-1,349.05,34.900,-349.05
182099,OI00182100,O0096397,P00040,2,330.75,992.250,661.50
183318,OI00183319,O0097029,P00538,1,122.19,183.285,122.19
190069,OI00190070,O0100555,P00775,-1,117.71,17.660,-117.71
191132,OI00191133,O0101115,P00117,-1,481.90,24.090,-481.90
193968,OI00193969,O0102625,P00458,4,301.26,1807.560,1205.04
209860,OI00209861,O0111126,P00050,1,135.60,203.400,135.60
216536,OI00216537,O0114645,P00554,-1,167.17,8.360,-167.17
221422,OI00221423,O0117244,P00227,1,857.92,1286.880,857.92

In [55]:
print("Negative quantity:", (order_items["quantity"] < 0).sum())
print("Zero quantity:", (order_items["quantity"] == 0).sum())
print("Negative price:", (order_items["unit_price"] < 0).sum())
print("Negative discount:", (order_items["discount_amount"] < 0).sum())
print(
    "Discount > gross value:",
    (order_items["discount_amount"] > order_items["gross_value"]).sum()
)

Negative quantity: 15
Zero quantity: 0
Negative price: 0
Negative discount: 0
Discount > gross value: 30

In [56]:
returns = pd.read_csv("../data/raw/returns.csv")

In [57]:
returns["order_item_id"].isin(
    order_items.loc[order_items["quantity"] < 0, "order_item_id"]
).value_counts()

order_item_id
False    13332
True         1
Name: count, dtype: int64

In [58]:
order_items_clean = order_items.copy()

In [59]:
order_items_clean = order_items_clean[
    order_items_clean["quantity"] > 0
].copy()

In [60]:
order_items_clean["gross_value"] = (
    order_items_clean["quantity"]
    * order_items_clean["unit_price"]
)

In [61]:
order_items_clean[
    order_items_clean["discount_amount"]
    > order_items_clean["gross_value"]
]

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount,gross_value
3216,OI00003217,O0001715,P00725,1,426.25,639.375,426.25
12051,OI00012052,O0006445,P00614,1,263.26,394.890,263.26
27456,OI00027457,O0014578,P00952,2,340.39,1021.170,680.78
56182,OI00056183,O0029727,P00089,2,337.09,1011.270,674.18
90704,OI00090705,O0047859,P00371,1,216.55,324.825,216.55
93594,OI00093595,O0049433,P00911,3,211.91,953.595,635.73
123840,OI00123841,O0065529,P00378,1,474.14,711.210,474.14
162065,OI00162066,O0085756,P00036,1,246.36,369.540,246.36
170741,OI00170742,O0090351,P00583,1,809.66,1214.490,809.66
178631,OI00178632,O0094565,P00818,1,138.59,207.885,138.59
182099,OI00182100,O0096397,P00040,2,330.75,992.250,661.50
183318,OI00183319,O0097029,P00538,1,122.19,183.285,122.19
193968,OI00193969,O0102625,P00458,4,301.26,1807.560,1205.04
209860,OI00209861,O0111126,P00050,1,135.60,203.400,135.60
221422,OI00221423,O0117244,P00227,1,857.92,1286.880,857.92

In [62]:
(order_items_clean["quantity"] <= 0).sum()

np.int64(0)

In [63]:
print("Original rows:", len(order_items))
print("Cleaned rows:", len(order_items_clean))
print("Rows removed:", len(order_items) - len(order_items_clean))

Original rows: 226739
Cleaned rows: 226724
Rows removed: 15

In [64]:
products = pd.read_csv("../data/raw/products.csv")
categories = pd.read_csv("../data/raw/categories.csv")

In [65]:
products.shape

(1000, 5)

In [66]:
products.isnull().sum()

product_id       0
product_name     0
category_id      0
brand           20
unit_cost        0
dtype: int64

In [67]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1000 non-null   str
 1   product_name  1000 non-null   str
 2   category_id   1000 non-null   str
 3   brand         980 non-null    str
 4   unit_cost     1000 non-null   float64
dtypes: float64(1), str(4)
memory usage: 72.3 KB

In [68]:
products.head(5)

  product_id   product_name category_id      brand  unit_cost
0     P00001  Product_00001      CAT007  Brand_056     201.06
1     P00002  Product_00002      CAT003  Brand_008      93.66
2     P00003  Product_00003      CAT008  Brand_040     154.95
3     P00004  Product_00004      CAT009  Brand_003     464.33
4     P00005  Product_00005      CAT003  Brand_088     461.40

In [69]:
products["product_id"].duplicated().sum()

np.int64(0)

In [70]:
products["unit_cost"].describe()

count    1000.000000
mean      200.946990
std       143.762368
min        24.100000
25%       107.077500
50%       160.870000
75%       250.935000
max      1112.570000
Name: unit_cost, dtype: float64

In [71]:
products[products["unit_cost"] <= 0]

Empty DataFrame
Columns: [product_id, product_name, category_id, brand, unit_cost]
Index: []

In [72]:

categories.shape

(12, 2)

In [73]:
categories.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category_id    12 non-null     str
 1   category_name  12 non-null     str
dtypes: str(2)
memory usage: 504.0 bytes

In [74]:
categories.head(12)

   category_id    category_name
0       CAT001      Electronics
1       CAT002          Fashion
2       CAT003   Home & Kitchen
3       CAT004           Beauty
4       CAT005           Sports
5       CAT006            Books
6       CAT007          Grocery
7       CAT008             Toys
8       CAT009        Furniture
9       CAT010      Accessories
10      CAT011    Personal Care
11      CAT012  Office Supplies

In [75]:
categories.isnull().sum()

category_id      0
category_name    0
dtype: int64

In [76]:
categories["category_id"].duplicated().sum()

np.int64(0)

In [77]:
categories["category_name"].value_counts()

category_name
Electronics        1
Fashion            1
Home & Kitchen     1
Beauty             1
Sports             1
Books              1
Grocery            1
Toys               1
Furniture          1
Accessories        1
Personal Care      1
Office Supplies    1
Name: count, dtype: int64

In [78]:
products["category_id"].isin(
    categories["category_id"]
).value_counts()

category_id
True    1000
Name: count, dtype: int64

In [79]:
products["brand"].isnull().sum()

np.int64(20)

In [80]:
payments = pd.read_csv("../data/raw/payments.csv")

In [81]:
payments.shape

(120000, 6)

In [82]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   payment_id      120000 non-null  str
 1   order_id        120000 non-null  str
 2   payment_method  120000 non-null  str
 3   payment_amount  120000 non-null  float64
 4   payment_date    120000 non-null  str
 5   payment_status  120000 non-null  str
dtypes: float64(1), str(5)
memory usage: 11.7 MB

In [83]:
payments.isnull().sum()

payment_id        0
order_id          0
payment_method    0
payment_amount    0
payment_date      0
payment_status    0
dtype: int64

In [84]:
payments.head(3)

,payment_id,order_id,payment_method,payment_amount,payment_date,payment_status
0,PAY0000001,O0000001,COD,88.29,2025-09-29 23:09:30,Successful
1,PAY0000002,O0000002,COD,1654.74,2024-03-18 01:29:25,Successful
2,PAY0000003,O0000003,Debit Card,178.74,2024-10-08 00:52:34,Refunded

In [85]:
payments["payment_id"].duplicated().sum()

np.int64(0)

In [86]:
payments["payment_status"].value_counts(dropna=False)

payment_status
Successful    112926
Failed          4169
Refunded        2905
Name: count, dtype: int64

In [87]:
payments["payment_amount"].describe()

count    120000.000000
mean        800.799136
std         736.160349
min          23.930000
25%         293.390000
50%         574.195000
75%        1066.760000
max       10102.210000
Name: payment_amount, dtype: float64

In [88]:
payments[payments["payment_amount"] <= 0]

Empty DataFrame
Columns: [payment_id, order_id, payment_method, payment_amount, payment_date, payment_status]
Index: []

In [89]:
payments["order_id"].isin(
    orders["order_id"]
).value_counts()

order_id
True    120000
Name: count, dtype: int64

In [90]:
payments["payment_method"].value_counts(dropna=False)

payment_method
UPI            40900
Credit Card    28892
Debit Card     18052
Net Banking    12004
COD            10643
Wallet          9509
Name: count, dtype: int64

In [91]:
returns.shape

(13333, 6)

In [92]:
returns = pd.read_csv("../data/raw/returns.csv")

In [93]:
returns.head(5)

,return_id,order_item_id,return_date,return_reason,return_quantity,refund_amount
0,R0000001,OI00215837,2025-05-03 02:34:39,Changed Mind,1,1756.38
1,R0000002,OI00166272,2025-02-10 23:42:40,Changed Mind,1,162.85
2,R0000003,OI00023461,2025-06-27 19:45:00,Size Issue,1,525.29
3,R0000004,OI00057792,2024-08-14 09:50:52,Size Issue,1,129.62
4,R0000005,OI00130020,2024-11-24 02:20:16,Wrong Product,1,227.94

In [94]:
returns.shape

(13333, 6)

In [95]:
returns.info()

<class 'pandas.DataFrame'>
RangeIndex: 13333 entries, 0 to 13332
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   return_id        13333 non-null  str
 1   order_item_id    13333 non-null  str
 2   return_date      13333 non-null  str
 3   return_reason    13333 non-null  str
 4   return_quantity  13333 non-null  int64
 5   refund_amount    13333 non-null  float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.2 MB

In [96]:
returns.isnull().sum()

return_id          0
order_item_id      0
return_date        0
return_reason      0
return_quantity    0
refund_amount      0
dtype: int64

In [97]:
returns["return_id"].duplicated().sum()

np.int64(0)

In [98]:
returns["return_quantity"].describe()

count    13333.000000
mean         1.067877
std          0.251544
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000
Name: return_quantity, dtype: float64

In [99]:
returns[returns["return_quantity"] <= 0]

Empty DataFrame
Columns: [return_id, order_item_id, return_date, return_reason, return_quantity, refund_amount]
Index: []

In [100]:
returns["refund_amount"].describe()

count    13333.000000
mean       327.334946
std        269.028128
min         23.930000
25%        160.780000
50%        250.080000
75%        399.680000
max       3550.110000
Name: refund_amount, dtype: float64

In [101]:
returns[returns["refund_amount"] < 0]

Empty DataFrame
Columns: [return_id, order_item_id, return_date, return_reason, return_quantity, refund_amount]
Index: []

In [102]:
returns["order_item_id"].isin(
    order_items["order_item_id"]
).value_counts()

order_item_id
True    13333
Name: count, dtype: int64

In [103]:
payments["payment_date"] = pd.to_datetime(payments["payment_date"])
returns["return_date"] = pd.to_datetime(returns["return_date"])

In [104]:
marketing = pd.read_csv("../data/raw/marketing.csv")

In [105]:
marketing.head(5)

,marketing_id,customer_id,acquisition_channel,campaign_id,acquisition_date,acquisition_cost
0,MKT0000001,C000001,Organic Search,CMP034,2025-01-30 05:14:27,45.04
1,MKT0000002,C000002,Facebook,CMP039,2024-10-18 21:17:16,364.54
2,MKT0000003,C000003,Organic Search,CMP027,2024-10-20 08:38:02,45.04
3,MKT0000004,C000004,Organic Search,CMP060,2023-09-02 00:03:08,26.22
4,MKT0000005,C000005,Facebook,CMP060,2023-06-04 02:38:12,262.27

In [106]:
marketing.shape
marketing.info()
marketing.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   marketing_id         30000 non-null  str
 1   customer_id          30000 non-null  str
 2   acquisition_channel  29800 non-null  str
 3   campaign_id          30000 non-null  str
 4   acquisition_date     30000 non-null  str
 5   acquisition_cost     30000 non-null  float64
dtypes: float64(1), str(5)
memory usage: 2.9 MB

marketing_id             0
customer_id              0
acquisition_channel    200
campaign_id              0
acquisition_date         0
acquisition_cost         0
dtype: int64

In [107]:
marketing["marketing_id"].duplicated().sum()

np.int64(0)

In [108]:
marketing["acquisition_channel"].value_counts(dropna=False)

acquisition_channel
Organic Search    8147
Google Ads        6498
Referral          4448
Instagram         4228
Facebook          3570
Email             2909
NaN                200
Name: count, dtype: int64

In [109]:
marketing["acquisition_cost"].describe()

count    30000.000000
mean       184.594766
std        132.328251
min         10.000000
25%         51.050000
50%        145.155000
75%        296.995000
max        627.580000
Name: acquisition_cost, dtype: float64

In [110]:
marketing[marketing["acquisition_cost"] < 0]

Empty DataFrame
Columns: [marketing_id, customer_id, acquisition_channel, campaign_id, acquisition_date, acquisition_cost]
Index: []

In [111]:
marketing["acquisition_date"] = pd.to_datetime(
    marketing["acquisition_date"]
)

In [112]:
marketing["acquisition_date"].min(), marketing["acquisition_date"].max()

(Timestamp('2023-01-01 00:53:32'), Timestamp('2025-12-30 23:08:37'))

In [113]:
marketing["customer_id"].isin(
    customers["customer_id"]
).value_counts()

customer_id
True    30000
Name: count, dtype: int64

In [114]:
experiment_sessions = pd.read_csv(
    "../data/raw/experiment_sessions.csv"
)

In [115]:
experiment_sessions.shape
experiment_sessions.info()
experiment_sessions.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   session_id     150000 non-null  str
 1   customer_id    150000 non-null  str
 2   experiment_id  150000 non-null  str
 3   variant        150000 non-null  str
 4   session_date   150000 non-null  str
 5   product_views  150000 non-null  int64
 6   added_to_cart  150000 non-null  int64
 7   purchased      150000 non-null  int64
dtypes: int64(3), str(5)
memory usage: 16.6 MB

session_id       0
customer_id      0
experiment_id    0
variant          0
session_date     0
product_views    0
added_to_cart    0
purchased        0
dtype: int64

In [116]:
experiment_sessions["variant"].value_counts(dropna=False)

variant
Control      75076
Treatment    74924
Name: count, dtype: int64

In [117]:
experiment_sessions["experiment_id"].value_counts()

experiment_id
EXP_001    150000
Name: count, dtype: int64

In [118]:
experiment_sessions[
    ["product_views", "added_to_cart", "purchased"]
].describe()

       product_views  added_to_cart      purchased
count  150000.000000  150000.000000  150000.000000
mean        2.635933       0.295487       0.093053
std         1.542826       0.456263       0.290508
min         1.000000       0.000000       0.000000
25%         1.000000       0.000000       0.000000
50%         2.000000       0.000000       0.000000
75%         4.000000       1.000000       0.000000
max         6.000000       1.000000       1.000000

In [119]:
experiment_sessions[
    (experiment_sessions["product_views"] < 0) |
    (experiment_sessions["added_to_cart"] < 0) |
    (experiment_sessions["purchased"] < 0)
]

Empty DataFrame
Columns: [session_id, customer_id, experiment_id, variant, session_date, product_views, added_to_cart, purchased]
Index: []

In [120]:
experiment_sessions["session_date"] = pd.to_datetime(
    experiment_sessions["session_date"]
)

In [121]:
experiment_sessions[
    experiment_sessions["added_to_cart"]
    > experiment_sessions["product_views"]
]

Empty DataFrame
Columns: [session_id, customer_id, experiment_id, variant, session_date, product_views, added_to_cart, purchased]
Index: []

In [122]:
experiment_sessions[
    (experiment_sessions["purchased"] > 0) &
    (experiment_sessions["added_to_cart"] == 0)
]

,session_id,customer_id,experiment_id,variant,session_date,product_views,added_to_cart,purchased
50,SES00000051,C004424,EXP_001,Treatment,2025-07-06 20:33:04,1,0,1
61,SES00000062,C006808,EXP_001,Treatment,2025-07-10 06:03:04,1,0,1
62,SES00000063,C017959,EXP_001,Control,2025-08-25 04:06:21,2,0,1
95,SES00000096,C021355,EXP_001,Control,2025-09-22 12:24:55,6,0,1
98,SES00000099,C026813,EXP_001,Treatment,2025-08-13 06:20:47,2,0,1
...,...,...,...,...,...,...,...,...
149969,SES00149970,C022916,EXP_001,Control,2025-09-14 13:47:39,2,0,1
149972,SES00149973,C029364,EXP_001,Treatment,2025-08-04 13:51:10,5,0,1
149977,SES00149978,C018967,EXP_001,Treatment,2025-07-14 11:31:09,3,0,1
149991,SES00149992,C007185,EXP_001,Control,2025-08-03 18:29:10,6,0,1
149992,SES00149993,C025660,EXP_001,Control,2025-08-23 20:34:06,6,0,1

# ShopSphere — Data Quality Summary

## Key Data Quality Findings

| Table | Issue | Business Impact | Decision |
|---|---|---|---|
| Customers | Missing city values | Affects city-level analysis | Retain records; handle missing city explicitly |
| Products | Missing brand values | Affects brand-level analysis | Retain products |
| Order Items | Invalid quantity values | Can distort revenue/profit | Investigate and clean invalid records |
| Marketing | Missing acquisition channel | Affects channel analysis | Handle missing values explicitly |
| Payments | Date/status validation | Affects revenue analysis | Validate before calculating revenue |
| Returns | Return quantity/refund validation | Affects net revenue and profit | Validate before analysis |
| Experiment Sessions | Event consistency | Affects A/B test validity | Validate before statistical analysis |

# Data Cleaning

The raw datasets are preserved unchanged. Cleaning decisions are based on the profiling results and documented business rules.

In [123]:
customers_clean = customers.copy()
orders_clean = orders.copy()
order_items_clean = order_items.copy()
products_clean = products.copy()
categories_clean = categories.copy()
payments_clean = payments.copy()
returns_clean = returns.copy()
marketing_clean = marketing.copy()
experiment_clean = experiment_sessions.copy()

In [124]:
customers_clean["signup_date"] = pd.to_datetime(
    customers_clean["signup_date"]
)

orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"]
)

payments_clean["payment_date"] = pd.to_datetime(
    payments_clean["payment_date"]
)

returns_clean["return_date"] = pd.to_datetime(
    returns_clean["return_date"]
)

marketing_clean["acquisition_date"] = pd.to_datetime(
    marketing_clean["acquisition_date"]
)

experiment_clean["session_date"] = pd.to_datetime(
    experiment_clean["session_date"]
)

In [125]:
customers_clean.duplicated().sum()

np.int64(50)

In [126]:
customers_clean[
    customers_clean.duplicated(keep=False)
].sort_values("customer_id")

,customer_id,customer_name,gender,age,state,signup_date,acquisition_channel,city
1023,C001024,Customer_001024,Female,18,Karnataka,2025-01-19 15:42:59,Referral,Bengaluru
30036,C001024,Customer_001024,Female,18,Karnataka,2025-01-19 15:42:59,Referral,Bengaluru
1139,C001140,Customer_001140,Male,60,Karnataka,2023-08-03 00:54:06,Email,Bengaluru
30019,C001140,Customer_001140,Male,60,Karnataka,2023-08-03 00:54:06,Email,Bengaluru
1252,C001253,Customer_001253,Male,23,Rajasthan,2025-01-24 07:56:43,Organic Search,Jaipur
...,...,...,...,...,...,...,...,...
30025,C027412,Customer_027412,Other,47,West Bengal,2024-01-16 18:44:04,Instagram,Kolkata
27928,C027929,Customer_027929,Female,44,Kerala,2023-12-19 08:35:21,Instagram,Kochi
30028,C027929,Customer_027929,Female,44,Kerala,2023-12-19 08:35:21,Instagram,Kochi
28663,C028664,Customer_028664,Other,42,Tamil Nadu,2025-12-27 18:14:38,Referral,Chennai
30018,C028664,Customer_028664,Other,42,Tamil Nadu,2025-12-27 18:14:38,Referral,Chennai

In [127]:
customers_clean = customers_clean.drop_duplicates().copy()

In [128]:
print("Remaining exact duplicates:",
      customers_clean.duplicated().sum())

print("Unique customer IDs:",
      customers_clean["customer_id"].nunique())

print("Rows:",
      len(customers_clean))

Remaining exact duplicates: 0
Unique customer IDs: 30000
Rows: 30000

In [129]:
customers_clean["city"].isnull().sum()

np.int64(300)

In [130]:
customers_clean["city"] = customers_clean["city"].fillna("Unknown")

In [131]:
customers_clean["city"].isnull().sum()

np.int64(0)

In [132]:
products_clean["brand"].isnull().sum()

np.int64(20)

In [133]:
products_clean["brand"] = products_clean["brand"].fillna("Unknown")

In [134]:
products_clean["brand"].isnull().sum()

np.int64(0)

In [135]:
marketing_clean["acquisition_channel"].isnull().sum()

np.int64(200)

In [136]:
marketing_clean["acquisition_channel"] = (
    marketing_clean["acquisition_channel"]
    .fillna("Unknown")
)

In [137]:
marketing_clean["acquisition_channel"].isnull().sum()

np.int64(0)

In [138]:
order_items_clean[order_items_clean["quantity"] < 0]

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount,gross_value
36873,OI00036874,O0019464,P00969,-1,588.42,88.26,-588.42
72989,OI00072990,O0038555,P00165,-1,337.05,0.00,-337.05
89183,OI00089184,O0047093,P00750,-1,448.10,134.43,-448.10
109838,OI00109839,O0058061,P00917,-1,129.58,58.31,-129.58
122825,OI00122826,O0064997,P00676,-1,133.11,19.97,-133.11
126107,OI00126108,O0066702,P00368,-1,143.97,43.19,-143.97
133020,OI00133021,O0070318,P00903,-1,267.00,0.00,-267.00
147669,OI00147670,O0078171,P00656,-1,223.36,22.34,-223.36
166958,OI00166959,O0088352,P00836,-1,224.23,0.00,-224.23
176574,OI00176575,O0093465,P00428,-1,177.98,0.00,-177.98
177152,OI00177153,O0093773,P00750,-1,448.10,44.81,-448.10
180496,OI00180497,O0095571,P00785,-1,349.05,34.90,-349.05
190069,OI00190070,O0100555,P00775,-1,117.71,17.66,-117.71
191132,OI00191133,O0101115,P00117,-1,481.90,24.09,-481.90
216536,OI00216537,O0114645,P00554,-1,167.17,8.36,-167.17

In [139]:
order_items_clean = order_items_clean[
    order_items_clean["quantity"] > 0
].copy()

In [140]:


order_items_clean["gross_value"] = (
    order_items_clean["quantity"]
    * order_items_clean["unit_price"]
)

In [141]:
order_items_clean[
    order_items_clean["discount_amount"]
    > order_items_clean["gross_value"]
]

,order_item_id,order_id,product_id,quantity,unit_price,discount_amount,gross_value
3216,OI00003217,O0001715,P00725,1,426.25,639.375,426.25
12051,OI00012052,O0006445,P00614,1,263.26,394.890,263.26
27456,OI00027457,O0014578,P00952,2,340.39,1021.170,680.78
56182,OI00056183,O0029727,P00089,2,337.09,1011.270,674.18
90704,OI00090705,O0047859,P00371,1,216.55,324.825,216.55
93594,OI00093595,O0049433,P00911,3,211.91,953.595,635.73
123840,OI00123841,O0065529,P00378,1,474.14,711.210,474.14
162065,OI00162066,O0085756,P00036,1,246.36,369.540,246.36
170741,OI00170742,O0090351,P00583,1,809.66,1214.490,809.66
178631,OI00178632,O0094565,P00818,1,138.59,207.885,138.59
182099,OI00182100,O0096397,P00040,2,330.75,992.250,661.50
183318,OI00183319,O0097029,P00538,1,122.19,183.285,122.19
193968,OI00193969,O0102625,P00458,4,301.26,1807.560,1205.04
209860,OI00209861,O0111126,P00050,1,135.60,203.400,135.60
221422,OI00221423,O0117244,P00227,1,857.92,1286.880,857.92

In [142]:
excess_discount_mask = (
    order_items_clean["discount_amount"]
    > order_items_clean["gross_value"]
)

print("Excessive discount rows:",
      excess_discount_mask.sum())

print("Total excessive discount amount:",
      (
          order_items_clean.loc[
              excess_discount_mask,
              "discount_amount"
          ].sum()
      ))

Excessive discount rows: 15
Total excessive discount amount: 11321.625

In [143]:
excess_discount_mask = (
    order_items_clean["discount_amount"]
    > order_items_clean["gross_value"]
)

print("Affected rows:", excess_discount_mask.sum())
print(
    "Affected gross value:",
    order_items_clean.loc[
        excess_discount_mask, "gross_value"
    ].sum()
)
print(
    "Affected discount amount:",
    order_items_clean.loc[
        excess_discount_mask, "discount_amount"
    ].sum()
)

Affected rows: 15
Affected gross value: 7547.75
Affected discount amount: 11321.625

In [144]:
order_items_clean = order_items_clean[
    ~excess_discount_mask
].copy()

In [145]:
print(
    "Invalid quantities:",
    (order_items_clean["quantity"] <= 0).sum()
)

print(
    "Discount > gross value:",
    (
        order_items_clean["discount_amount"]
        > order_items_clean["gross_value"]
    ).sum()
)

print("Original rows:", len(order_items))
print("Cleaned rows:", len(order_items_clean))
print("Rows removed:", len(order_items) - len(order_items_clean))

Invalid quantities: 0
Discount > gross value: 0
Original rows: 226739
Cleaned rows: 226709
Rows removed: 30

In [146]:
order_items_clean["net_item_value"] = (
    order_items_clean["gross_value"]
    - order_items_clean["discount_amount"]
)

In [147]:
print("Customers:", customers_clean.shape)
print("Orders:", orders_clean.shape)
print("Order items:", order_items_clean.shape)
print("Products:", products_clean.shape)
print("Categories:", categories_clean.shape)
print("Payments:", payments_clean.shape)
print("Returns:", returns_clean.shape)
print("Marketing:", marketing_clean.shape)
print("Experiment:", experiment_clean.shape)

Customers: (30000, 8)
Orders: (120000, 6)
Order items: (226709, 8)
Products: (1000, 5)
Categories: (12, 2)
Payments: (120000, 6)
Returns: (13333, 6)
Marketing: (30000, 6)
Experiment: (150000, 8)

In [148]:
customers_clean.to_csv("../data/processed/customers.csv", index=False)
orders_clean.to_csv("../data/processed/orders.csv", index=False)
order_items_clean.to_csv("../data/processed/order_items.csv", index=False)
products_clean.to_csv("../data/processed/products.csv", index=False)
categories_clean.to_csv("../data/processed/categories.csv", index=False)
payments_clean.to_csv("../data/processed/payments.csv", index=False)
returns_clean.to_csv("../data/processed/returns.csv", index=False)
marketing_clean.to_csv("../data/processed/marketing.csv", index=False)
experiment_clean.to_csv("../data/processed/experiment_sessions.csv", index=False)